// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqtiriwtohdsbjonstjb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxdGlyaXd0b2hkc2Jqb25zdGpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMjUxNjEsImV4cCI6MjA2NDkwMTE2MX0.aGO_xj-WRiV0x37MqGnNjgJ6qEwfGdeVeQksu6KTpG0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);