name: Supabase Migrations Otomatik Aktarım

on:
  push:
    paths:
      - 'supabase/migrations/**.sql'
      - '.github/workflows/supabase-migrations.yml'

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Supabase CLI yükle
        run: |
          npm install -g supabase
      - name: .env dosyasını ayarla
        run: |
          echo "SUPABASE_ACCESS_TOKEN=${{ secrets.SUPABASE_ACCESS_TOKEN }}" >> $GITHUB_ENV
          echo "SUPABASE_PROJECT_REF=nujvwfoquvtqoebzkhtr" >> $GITHUB_ENV
      - name: Migration dosyalarını cloud'a aktar
        run: |
          supabase link --project-ref $SUPABASE_PROJECT_REF
          supabase db push --project-ref $SUPABASE_PROJECT_REF
